import type { ServiceItem } from "./types";

export const NAV_LINKS = ["Services", "Works", "Stories", "Contact"] as const;

export const PLATFORM_COLORS: Record<string, string> = {
  linkedin:  "#0A66C2",
  facebook:  "#1877F2",
  twitter:   "#1DA1F2",
  instagram: "#E4405F",
  website:   "#0d0d0d",
  other:     "#0d0d0d",
};

export const SERVICES: ServiceItem[] = [
  {
    id: "smart-website-builds",
    slug: "smart-website-builds",
    title: "Smart Website Builds",
    tag: "WEB",
    price: "KES 45,000",
    currency: "KES",
    priceNote: "starting from",
    shortDescription: "AI-native websites engineered for performance, automation, SEO, and intelligent user experiences.",
    description: "AI-native websites engineered for performance, automation, SEO, and intelligent user experiences. From landing pages to full platforms.",
    features: [
      "Custom AI chat integrations",
      "SEO-optimised architecture",
      "CMS & content automation",
      "Mobile-first, blazing fast",
    ],
    imageUrl: "",
    published: true,
    order: 1,
    seoTitle: "",
    seoDescription: "",
  },
  {
    id: "business-automation",
    slug: "business-automation",
    title: "Business Automation",
    tag: "AUTOMATE",
    price: "KES 35,000",
    currency: "KES",
    priceNote: "per workflow",
    shortDescription: "Automate repetitive operations, connect business tools, and streamline customer and internal workflows.",
    description: "End-to-end automation of your business operations — CRM syncs, email sequences, data pipelines, and AI-powered decision flows.",
    features: [
      "Zapier / Make / n8n builds",
      "CRM & lead automation",
      "Invoice & ops workflows",
      "WhatsApp & email bots",
    ],
    imageUrl: "",
    published: true,
    order: 2,
    seoTitle: "",
    seoDescription: "",
  },
  {
    id: "ai-strategy-integration",
    slug: "ai-strategy-integration",
    title: "AI Strategy & Integration",
    tag: "AI",
    price: "KES 60,000",
    currency: "KES",
    priceNote: "per engagement",
    shortDescription: "Integrate AI into your products and processes through LLM APIs, strategic consulting, and tailored solutions.",
    description: "Custom AI integrations, LLM deployments, and strategic consulting to embed AI into your product or business process.",
    features: [
      "GPT / Claude API integration",
      "Custom AI model fine-tuning",
      "AI audit & roadmap",
      "Vendor selection support",
    ],
    imageUrl: "",
    published: true,
    order: 3,
    seoTitle: "",
    seoDescription: "",
  },
  {
    id: "ai-training-programmes",
    slug: "ai-training-programmes",
    title: "AI Training Programmes",
    tag: "TRAIN",
    price: "KES 15,000",
    currency: "KES",
    priceNote: "per person",
    shortDescription: "Practical AI training designed to help individuals and teams apply AI tools to real business challenges.",
    description: "Hands-on workshops and training programmes for teams transitioning to AI-first workflows. Practical, not theoretical.",
    features: [
      "Team AI literacy bootcamp",
      "Prompt engineering labs",
      "Tool adoption coaching",
      "Ongoing support retainer",
    ],
    imageUrl: "",
    published: true,
    order: 4,
    seoTitle: "",
    seoDescription: "",
  },
];
